### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by leanderriefel** [jorroll/solid-forms#11]
Not sure if this is my fault or the libraries but when running in a dev environment (solid-start) I get the following error:

```
An error occured while server rendering /app:

	Cannot use import statement outside a module

...\node_modules\solid-forms\dist\public-api\index.module.js:1
import { isAbstractControlContainer } from 'solid-forms/core';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25
```

**Comment by jorroll** [comment]
Is `solid-forms` your only import in this file? If you remove the `solid-forms` import does this error go away?

**Comment by leanderriefel** [comment]
removing the `solid-forms` imports or uninstalling the package makes this error go away.
I just copy pasted the `TextInput` and `ExampleForm` examples into my project.
Could also be on my end but not sure as every other package works.

**Comment by leanderriefel** [comment]
the error from above is also just an example that was displayed first. my console gets spammed with import errors from the `solid-forms` package (`SyntaxError: Cannot use import statement outside a module`), so its not just that single file if that helps.

**Comment by jorroll** [comment]
I just created a new `solid-start` project and copied the TextInput example code in. Everything seems to work. It looks like `solid-start` still has some rough edges to it though. E.g. changing some dependencies caused it to crash but simply restarting everything appeared to fix the problems.

So sort version is that I'm not sure why you might be running into these errors. Build errors can also be hard to diagnose. E.g. it's possible that simply removing all dependencies and reinstalling everything would make the error go away, or it could be some config setting somewhere or any number of other things.

**Comment by jorroll** [comment]
> the error from above is also just an example that was displayed first. my console gets spammed with import errors from the `solid-forms` package (`SyntaxError: Cannot use import statement outside a module`), so its not just that single file if that helps.

If `solid-start` is failing to recognize that `solid-forms` is an ES6 module, I'm not surprised that you're seeing a bunch of files reporting that `SyntaxError: Cannot use import statement outside a module`. It looks like `solid-start` is attempting to import from the  solid-forms `module` entrypoint which uses module syntax for all the files. solid-forms also provides a commonjs entrypoint in `main`. 

It's also possible that the real error isn't the one that's being surfaced in the console and it's something else that is causing things to fail.

**Comment by leanderriefel** [comment]
Creating a new project with create-jd-app (tailwind) and just adding solid-forms also produces the error for me (same with `npm init solid@latest`).
Still not sure if this is on my end or something but this is the github repo: https://github.com/xNoobyyy/solid-forms-test

**Comment by leanderriefel** [comment]
Building the code and then running it works for me. Has to be some configuration set up wrong, right?
if you someone can maybe check the repo above and test if the error is reproducable there :)?
If not, ig you can close this for now and I'll look into my configs and stuff.

**Comment by leanderriefel** [comment]
Hello again, so going into my `node_modules` and into the `package.json` from solid-forms and changing `"exports" -> "." -> "import"` from `"./dist/public-api/index.module.js"` to `"./dist/public-api/index.common.js"` fixes it.

Ik this is really hacky and I cant really "fix" it that way, as it will just reset after npm installing. Still not sure if its my fault or the packages ¯\_(ツ)_/¯

**Comment by jorroll** [comment]
> Creating a new project with create-jd-app (tailwind)

I tried cloning your repo and running it. I see the same error you described. I presume it's related to this 3rd party `create-jd-app` config you're using. You should use the [official `solid-start` template](https://start.solidjs.com/getting-started/project-setup). It supports tailwind.

**Comment by leanderriefel** [comment]
same error for me with the official solid-start template (https://github.com/xNoobyyy/solid-forms-test-2).
if you could maybe share your project that you were testing with so I can compare the two, sry if its all too much work.

**Comment by jorroll** [comment]
> if you could maybe share your project that you were testing with so I can compare the two

Here it is @xNoobyyy: https://github.com/jorroll/solid-forms-issue-11

The repo shows pnpm as the package manager, but I've confirmed it also works with NPM.

**Comment by leanderriefel** [comment]
got it working, tysm
