### ISSUE TITLE
createFormArray Always Sets required to True Despite options Specification

### ISSUE THREAD

**Issue by corbolt** [jorroll/solid-forms#13]
The createFormArray function is currently exhibiting unexpected behavior. Even when the options parameter specifies { required: false }, it always sets the required property of the resulting IFormArray object to true. This issue does not occur when initializing the array with an empty array (createFormArray([])).

This behavior is causing problems when dealing with scenarios where only some of the FormGroup fields are required. It's essential to clarify that having some required fields within the FormGroup should not necessarily force the entire array to be marked as required.

For example, consider a case where you're asked to input family members with fields like firstname, lastname, and age, all of which are required. However, you might not be required to input any family members initially, and the array should be allowed to be empty. When you do add a record, that individual record should be validated.

The issue here is that a straightforward check on array.isRequired is insufficient because it appears to be automatically determined based on the child elements, which isn't the desired behavior.

This behavior needs to be optimized to ensure that the createFormArray function respects the required option properly, allowing for arrays with optional initial records while correctly reflecting the required status of individual records within the array.

**Comment by corbolt** [comment]
Forget what i just wrote. The behavior is actually correct: The Array switches from required to not required when all blocks are deleted.

**Comment by jorroll** [comment]
Sounds like you figured it out, but just in case anyone else is looking at this: `AbstractControlContainer` objects (i.e. FormGroup and FormArray) exhibit `control.isRequired === true` if either `control.self.isRequired || control.child.isRequired`. 

For example:

```ts
// control.isRequired === false
const control = createFormArray([ ])

const child = createFormControl(null, { required: true });

// control.isRequired === true (and also control.self.isRequired === false)
control.push(child);

// control.isRequired === false
control.removeControl(child);

// control.isRequired === true (and also control.self.isRequired === true)
control.markRequired(true);
// or
const control = createFormArray([], { required: true })
```
