### ISSUE TITLE
Cannot mutate a Store directly

### ISSUE THREAD

**Issue by kapilpipaliya** [jorroll/solid-forms#4]
Cannot mutate a Store directly
```
       const owner = getOwner();
       const attrs= createFormArray([]);
       ...
        runWithOwner(owner, () => {
            attrs.controls.splice(toIndex, 0, ...attrs.controls.splice(fromIndex, 1));
            for (let i = 0; i < attrs.controls.length; i++) {
              attrs.attrsontrols[i].controls.pos.setValue(i + 1);
            }
        });
```

**Comment by jorroll** [comment]
Correct, you need to use the built in methods. I'm very sorry that I don't appear to have mentioned this in the docs, but `solid-forms` is immutable unless using the built-in methods. Not mentioning that is a big oversight on my part. I'll correct that and update the docs to make clear that the API is immutable unless using the built-in methods.

You can see the methods on FormArray here: https://github.com/jorroll/solid-forms#iformarray

**Comment by kapilpipaliya** [comment]
Thanks for the quick response. can you give me a way to modify array element positions, if possible?

**Comment by jorroll** [comment]
Hey @kapilpipaliya, I expect this will work for you:

```ts
// first we clone the control's `controls` value
const controls = [ ...attrs.controls ] // or attrs.controls.slice()
// then we mutate the cloned `controls` value
controls.splice(toIndex, 0, ...controls.splice(fromIndex, 1));
// then we use the `setControls()` method to update the control's `controls` value
attrs.setControls(controls);
// etc...
```

**Comment by jorroll** [comment]
I don't think it matters for your example, but, as mentioned in the [Getting Started section](https://github.com/jorroll/solid-forms#getting-started), `solid-forms` just uses the [Solidjs `Store` object](https://www.solidjs.com/docs/latest/api#createstore) under the hood. Solidjs stores wrap nested objects in proxies. If this is ever a problem or annoying (e.g. using `console.log` to inspect values in the browser) you can use the [Solidjs `unwrap` function](https://www.solidjs.com/docs/latest/api#unwrap) to access the original, non-proxied, control object.

**Comment by jorroll** [comment]
I updated the readme in multiple places to note that `solid-forms` control objects are immutable unless you use the provided methods to update their state.
